// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Product.API.Data;

#nullable disable

namespace Product.API.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    partial class ProductDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Product.API.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "Mobile"
                        },
                        new
                        {
                            Id = 2,
                            Title = "Laptop"
                        });
                });

            modelBuilder.Entity("Product.API.Entities.Products", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Oneplus Mobile",
                            ImageUrl = "https://fdn2.gsmarena.com/vv/pics/oneplus/oneplus-nord-2t-5g-1.jpg",
                            Price = 35000.00m,
                            Title = "Nord 2T"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Apple Mobile",
                            ImageUrl = "https://technextgroup.com/wp-content/uploads/2022/03/Tech-Next-Store-iPhone-13-Pro-Starlight1-1.jpg",
                            Price = 50000.00m,
                            Title = "IPhone 13"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "Oneplus Mobile",
                            ImageUrl = "https://fdn2.gsmarena.com/vv/pics/oneplus/oneplus-nord-2t-5g-1.jpg",
                            Price = 35000.00m,
                            Title = "Nord 2T"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "Oneplus Mobile",
                            ImageUrl = "https://fdn2.gsmarena.com/vv/pics/oneplus/oneplus-nord-2t-5g-1.jpg",
                            Price = 35000.00m,
                            Title = "Nord 2"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Description = "Oneplus Mobile",
                            ImageUrl = "https://fdn2.gsmarena.com/vv/pics/oneplus/oneplus-nord-2t-5g-1.jpg",
                            Price = 45000.00m,
                            Title = "11R"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Description = "Oneplus Mobile",
                            ImageUrl = "https://fdn2.gsmarena.com/vv/pics/oneplus/oneplus-nord-2t-5g-1.jpg",
                            Price = 35000.00m,
                            Title = "Nord 2T"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            Description = "Dell Laptop",
                            ImageUrl = "https://e0.pxfuel.com/wallpapers/939/934/desktop-wallpaper-dell-xps-15-xps9550-4444slv-15-6-inch-traditional-laptop-dell-xps-ultra.jpg",
                            Price = 70000.00m,
                            Title = "XPS 15"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
